# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 22:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_body', models.TextField()),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Properties')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('country', models.CharField(max_length=50)),
                ('default_currency', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('BR', 'Buyer/Renter'), ('PO', 'Private Owner'), ('B', 'Broker'), ('RC', 'Real Estate Company')], max_length=2)),
                ('image', models.ImageField(upload_to=b'')),
                ('points', models.IntegerField()),
                ('social_media', models.BooleanField(default=False)),
                ('messages', models.ManyToManyField(through='accounts.UserMessages', to='accounts.UserProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usermessages',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='accounts.UserProfile'),
        ),
        migrations.AddField(
            model_name='usermessages',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='accounts.UserProfile'),
        ),
    ]
