# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160325_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='img_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='img_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, height_field='img_height', null=True, upload_to=b'', width_field='img_width'),
        ),
    ]
