# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160328_2317'),
        ('accounts', '0002_auto_20160330_1102'),
    ]

    operations = [
    ]
