# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 16:45
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160325_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, height_field='img_height', null=True, upload_to=accounts.models.upload_location, width_field='img_width'),
        ),
    ]
