# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproperties',
            name='property_type',
            field=models.CharField(choices=[('Appartment', 'Appartment'), ('Building', 'Building'), ('Land', 'Land'), ('Villa', 'Villa'), ('Store', 'Store'), ('Office', 'Office')], max_length=1),
        ),
    ]
