# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 08:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribtions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('neighborhood', models.CharField(max_length=50)),
                ('property_type', models.CharField(choices=[('a', 'Appartment'), ('b', 'Building'), ('l', 'Land'), ('v', 'Villa'), ('s', 'Store'), ('o', 'Office')], max_length=1)),
                ('property_categories', models.CharField(choices=[('s', 'For Sale'), ('r', 'For Rent')], max_length=1)),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
