# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
