# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prop_photos',
            old_name='prop_id',
            new_name='prop',
        ),
    ]
