# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 20:24
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_properties_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='lon',
        ),
        migrations.AddField(
            model_name='properties',
            name='position',
            field=geoposition.fields.GeopositionField(default='Null', max_length=42),
        ),
    ]
