# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20160322_2229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prop_Photos',
            new_name='PropertiesPhotos',
        ),
    ]
