# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20160330_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='prop_type',
            field=models.CharField(choices=[('Appartment', 'Appartment'), ('Building', 'Building'), ('Land', 'Land'), ('Villa', 'Villa'), ('Store', 'Store'), ('Office', 'Office')], max_length=20),
        ),
    ]
