# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20160324_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='position',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
    ]
