# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20160324_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='lon',
        ),
    ]
